# Generated by Django 5.1.1 on 2024-09-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_name', models.CharField(default='X', max_length=1)),
                ('max_acceleration', models.FloatField(default=200)),
                ('max_velocity', models.FloatField(default=60)),
                ('actual_position', models.FloatField(default=0)),
                ('target_position', models.FloatField(default=0)),
                ('distance_to_go', models.FloatField(default=0)),
                ('homed', models.BooleanField(default=False)),
                ('acceleration', models.FloatField(default=0)),
                ('velocity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100)),
                ('tool_capacity', models.IntegerField(default=24)),
                ('tool_offset', models.FloatField(default=14.5)),
                ('feedrate', models.FloatField(default=10000)),
                ('tool_in_use', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AxisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actual_position', models.FloatField()),
                ('target_position', models.FloatField()),
                ('distance_to_go', models.FloatField()),
                ('homed', models.BooleanField()),
                ('velocity', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('machine_tool_offset', models.FloatField()),
                ('machine_feedrate', models.FloatField()),
                ('machine_tool_in_use', models.IntegerField()),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='axis.axis')),
            ],
        ),
        migrations.AddField(
            model_name='axis',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='axis.machine'),
        ),
        migrations.AddConstraint(
            model_name='axis',
            constraint=models.UniqueConstraint(fields=('machine', 'axis_name'), name='unique_machine_axis'),
        ),
    ]
