# Generated by Django 5.1.1 on 2024-09-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('supervisor', 'Supervisor')], default='operator', max_length=20),
        ),
    ]
